services:
  clickhouse:
    # Upgrade from 24.3 to check behaviour on new events table.
    # Unit tests still verify 24.3 behaviour using -azure and -redis-cluster configs.
    image: docker.io/clickhouse/clickhouse-server:25.8
    user: "101:101"
    container_name: ${CLICKHOUSE_CONTAINER_NAME:-langfuse-clickhouse}
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    ports:
      - ${HOST_IP:-127.0.0.1}:${CLICKHOUSE_HTTP_PORT:-8123}:8123
      - ${HOST_IP:-127.0.0.1}:${CLICKHOUSE_NATIVE_PORT:-9005}:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
    depends_on:
      - postgres
    networks:
      - default

  minio:
    image: cgr.dev/chainguard/minio
    container_name: ${MINIO_CONTAINER_NAME:-langfuse-minio}
    entrypoint: sh
    # create the 'langfuse' bucket before starting the service
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniosecret}
    ports:
      - ${HOST_IP:-127.0.0.1}:${MINIO_API_PORT:-9090}:9000
      - ${HOST_IP:-127.0.0.1}:${MINIO_CONSOLE_PORT:-9091}:9001
    volumes:
      - langfuse_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
    networks:
      - default

  redis:
    image: docker.io/redis:7.2.4
    container_name: ${REDIS_CONTAINER_NAME:-langfuse-redis}
    restart: always
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
      --maxmemory-policy noeviction
    ports:
      - ${HOST_IP:-127.0.0.1}:${REDIS_HOST_PORT:-6379}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_AUTH:-myredissecret}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 1s
    networks:
      - default

  postgres:
    image: docker.io/postgres:${POSTGRES_VERSION:-17}
    container_name: ${POSTGRES_CONTAINER_NAME:-langfuse-postgres}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=UTC
      - PGTZ=UTC
    ports:
      - ${HOST_IP:-127.0.0.1}:${POSTGRES_HOST_PORT:-5432}:5432
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
    networks:
      - default

  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3
    container_name: ${WORKER_CONTAINER_NAME:-langfuse-worker}
    restart: always
    depends_on: &langfuse-depends-on
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:3030:3030"
    environment: &langfuse-worker-env
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-postgres}
      SALT: ${SALT:-mysalt}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-0000000000000000000000000000000000000000000000000000000000000000}
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:9000
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse}
      CLICKHOUSE_CLUSTER_ENABLED: "false"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_AUTH: ${REDIS_AUTH:-myredissecret}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minio}
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-miniosecret}
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: auto
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minio}
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-miniosecret}
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: http://minio:9000
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
    networks:
      - default

  langfuse-web:
    image: docker.io/langfuse/langfuse:3
    container_name: ${LANGFUSE_CONTAINER_NAME:-langfuse-web}
    restart: always
    depends_on: *langfuse-depends-on
    ports:
      - "${HOST_IP:-0.0.0.0}:${LANGFUSE_PORT:-3100}:3000"
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-mysecret}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3100}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/public/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - default

volumes:
  langfuse_postgres_data:
    name: ${POSTGRES_VOLUME_NAME:-langfuse_postgres_data}
    driver: local
  langfuse_clickhouse_data:
    name: ${CLICKHOUSE_DATA_VOLUME_NAME:-langfuse_clickhouse_data}
    driver: local
  langfuse_clickhouse_logs:
    name: ${CLICKHOUSE_LOGS_VOLUME_NAME:-langfuse_clickhouse_logs}
    driver: local
  langfuse_minio_data:
    name: ${MINIO_VOLUME_NAME:-langfuse_minio_data}
    driver: local

networks:
  default:
    name: ${DOCKER_NETWORK_NAME:-langfuse-network}
    driver: bridge